FROM node:16 as my-build
WORKDIR /app

COPY /front/package.json ./
COPY /front/package-lock.json ./

RUN npm install

COPY . .

WORKDIR /app/front
RUN npm run build

FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=my-build /app/front/build /usr/share/nginx/html

COPY /nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
